model:
  name: resnet50
  num_classes: 100
  pretrained: false
  zero_init_residual: false
  groups: 1
  width_per_group: 64
  replace_stride_with_dilation: null

data:
  dataset_name: cifar100
  data_dir: ./data
  batch_size: 64
  num_workers: 4
  train_split: 0.8
  augmentation: true
  normalize: true

training:
  epochs: 300
  learning_rate: 0.05
  weight_decay: 1e-4
  momentum: 0.9
  scheduler_type: cosine
  scheduler_params: null
  mixed_precision: true
  gradient_clipping: null
  early_stopping_patience: 30
  save_every_n_epochs: 10

logging:
  log_level: INFO
  log_file: training.log
  experiment_name: cifar100_resnet50
  save_dir: ./checkpoints
  tensorboard_log_dir: ./logs/tensorboard
  wandb_project: null
  wandb_entity: null
